In [41]:
import numpy as np
list_ = [ "1" , "2" , "3" , "4" , "5"]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [42]:
type(array_list)

numpy.ndarray

In [43]:
type(list)

<class 'list'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [44]:
type(list[0:4])

types.GenericAlias

In [45]:
type(array_list)

numpy.ndarray

Q3. Considering the following changes in the variable, array_list:

In [46]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [47]:
type(array_list)

numpy.ndarray

In [62]:
type("print list_")

str

In [63]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:                                          
(i) shape                                                                        
(ii) size                                                                                               

In [65]:
num_array.shape

(2, 3)

In [66]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [68]:
# Python Program to create array with all zeros 
import numpy as geek  
b = geek.zeros([3, 3], dtype = int)  
print("\nMatrix b : \n", b) 


Matrix b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [84]:
import numpy as geek  
  
b = geek.diagonal([5, 5])  
print("\nMatrix b : \n", b) 

ValueError: diag requires an array of at least two dimensions